name: 'bdeat3dbt'
version: '1.0.0'
config-version: 2

profile: 'bdeat3dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  bdeat3dbt:
    example:
      +materialized: view
