sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw
    tables:
      - name: LGA
      - name: listings
      - name: residents
      - name: aggregates
      - name: suburb
